apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-conversion
  namespace: default
  labels:
    app: currency-conversion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-conversion
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
        - name: mmv2-currency-conversion-service
          image: in28min/mmv3-currency-conversion-service:0.0.12-SNAPSHOT
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: currency-conversion
      restartPolicy: Always
